import { ThemeColors } from "@/theme/theme";
// ─── Orders Mock Data ────────────────────────────────────────────────────────

export const ORDERS = [
  {
    id: 'ORD-921',
    customer: { name: 'Ariel Hikmat', initials: 'A4', color: ThemeColors.blue },
    status: 'Ready',
    type: 'Dine In',
    table: 'A4',
    date: 'Wed, July 12, 2023',
    time: '06:12 PM',
    items: [
      { name: 'Scrambled eggs with toast', qty: 1, price: 16.99 },
      { name: 'Smoked Salmon Bagel', qty: 1, price: 18.49 },
      { name: 'Belgian Waffles', qty: 2, price: 38.98 },
      { name: 'Classic Lemonade', qty: 1, price: 12.49 },
    ],
    total: 87.34,
    station: null,
  },
  {
    id: 'ORD-921',
    customer: { name: 'Denis Freeman', initials: 'B2', color: ThemeColors.blue },
    status: 'In Progress',
    type: 'Takeaway',
    date: 'Wed, July 12, 2023',
    time: '06:18 PM',
    items: [
      { name: 'Classic Cheeseburger', qty: 1, price: 10.99 },
      { name: 'Fish and Chips', qty: 2, price: 34.00 },
      { name: 'Greek Gyro Plate', qty: 1, price: 13.99 },
    ],
    total: 57.87,
    station: 'Cooking Now',
  },
  {
    id: 'ORD-916',
    customer: { name: 'Morgan Cox', initials: 'TA', color: ThemeColors.amber },
    status: 'In Progress',
    type: 'Takeaway',
    date: 'Wed, July 12, 2023',
    time: '06:19 PM',
    items: [
      { name: 'Vegetarian Pad Thai', qty: 1, price: 16.99 },
      { name: 'Shrimp Tacos', qty: 2, price: 19.49 },
      { name: 'Belgian Waffles', qty: 2, price: 38.98 },
      { name: 'Falafel Coffee', qty: 1, price: 11.00 },
    ],
    total: 86.96,
    station: 'In the Kitchen',
    extraItems: 2,
  },
  {
    id: 'ORD-925',
    customer: { name: 'Paul Rey', initials: 'TA', color: ThemeColors.amber },
    status: 'In Progress',
    type: 'Takeaway',
    date: 'Wed, July 12, 2023',
    time: '06:18 PM',
    items: [
      { name: 'Margherita Pizza', qty: 1, price: 16.99 },
      { name: 'Belgian Waffles', qty: 1, price: 19.49 },
      { name: 'Virgin Mojito', qty: 2, price: 25.98 },
      { name: 'Classic Lemonade', qty: 2, price: 25.98 },
    ],
    total: 87.06,
    station: 'In the Kitchen',
  },
  {
    id: 'ORD-912',
    customer: { name: 'Maja Becker', initials: 'A9', color: ThemeColors.blue },
    status: 'Completed',
    type: 'Dine In',
    table: 'A9',
    date: 'Wed, July 12, 2023',
    time: '05:32 PM',
    items: [
      { name: 'Feta Stuffed Mushrooms', qty: 1, price: 18.99 },
      { name: 'Lobster Ravioli', qty: 2, price: 17.99 },
      { name: 'Thai Coconut Curry', qty: 2, price: 14.49 },
      { name: 'Salmon Waffles', qty: 3, price: 35.00 },
    ],
    total: 98.34,
    station: 'Waiting for Payment',
    extraItems: 4,
  },
  {
    id: 'ORD-908',
    customer: { name: 'Erwan Richard', initials: 'C2', color: ThemeColors.blue },
    status: 'Completed',
    type: 'Dine In',
    table: 'C2',
    date: 'Wed, July 12, 2023',
    time: '05:20 PM',
    items: [
      { name: 'Creamy Garlic Chicken', qty: 1, price: 15.99 },
      { name: 'Greek Gyro Plate', qty: 1, price: 13.99 },
      { name: 'Belgian Waffles', qty: 2, price: 12.99 },
      { name: 'Iced Tea Infusion', qty: 1, price: 9.00 },
    ],
    total: 56.96,
    station: 'Waiting for Payment',
    extraItems: 3,
  },
];

export const STATUS_CONFIG = {
  Ready: { color: ThemeColors.emerald, bg: ThemeColors.emeraldDim, icon: '✓' },
  'In Progress': { color: ThemeColors.amber, bg: ThemeColors.amberDim, icon: '⏳' },
  Completed: { color: ThemeColors.blue, bg: ThemeColors.blueDim, icon: '✓' },
};
